### ISSUE TITLE
How can we generate scannet_2cm_sdf.

### ISSUE THREAD

**Issue by saladcat** [yuchenrao/PatchComplete#1]
Thanks for your great works, I find there are some data missing here. How can I generate 'your/path/to/scannet/scannet_2cm_sdf' which used in 2.Extract SDF inputs from ScanNet scenes

'''
python data_processing/generate_sdfs_from_scannet_scenes.py --sdf_path your/path/to/scannet/scannet_2cm_sdf --scan_path your/path/to/ScanNet/public/v2/scans --mask_path dataset_samples/scannet
'''

**Comment by yuchenrao** [comment]
Hi, 

Thanks a lot for your interest. You need to sign the agreements for ScanNet and ShapeNet to get the dataset from their original website first, and then use these datasets as the original. 
We'll try to release our own dataset as well (try to figure out how now).

ShapeNet:https://shapenet.org ; ScanNet: https://github.com/ScanNet/ScanNet

Best,
Yuchen

**Comment by yuchenrao** [comment]
> Thanks for your great works, I find there are some data missing here. How can I generate 'your/path/to/scannet/scannet_2cm_sdf' which used in 2.Extract SDF inputs from ScanNet scenes
> 
> ''' python data_processing/generate_sdfs_from_scannet_scenes.py --sdf_path your/path/to/scannet/scannet_2cm_sdf --scan_path your/path/to/ScanNet/public/v2/scans --mask_path dataset_samples/scannet '''

Hi,

Thanks a lot for your interest. You need to sign the agreements for ScanNet and ShapeNet to get the dataset from their original website first, and then use these datasets as the original.
We'll try to release our own dataset as well (try to figure out how now).

ShapeNet: https://shapenet.org/ ; ScanNet: https://github.com/ScanNet/ScanNet

Best,
Yuchen

**Comment by saladcat** [comment]
> > Thanks for your great works, I find there are some data missing here. How can I generate 'your/path/to/scannet/scannet_2cm_sdf' which used in 2.Extract SDF inputs from ScanNet scenes
> > ''' python data_processing/generate_sdfs_from_scannet_scenes.py --sdf_path your/path/to/scannet/scannet_2cm_sdf --scan_path your/path/to/ScanNet/public/v2/scans --mask_path dataset_samples/scannet '''
> 
> Hi,
> 
> Thanks a lot for your interest. You need to sign the agreements for ScanNet and ShapeNet to get the dataset from their original website first, and then use these datasets as the original. We'll try to release our own dataset as well (try to figure out how now).
> 
> ShapeNet: https://shapenet.org/ ; ScanNet: https://github.com/ScanNet/ScanNet
> 
> Best, Yuchen

Thanks for you quickly reply. I have downloaded the scannet datasets, but there is no sdf data here. I am not sure how you generate sdf files. Is ok to use this repo https://github.com/andyzeng/tsdf-fusion-python? And there are some params that didn't be figure out in origin paper. Can you help to figure it out? Thanks!!

Shiyang

**Comment by yuchenrao** [comment]
> > > Thanks for your great works, I find there are some data missing here. How can I generate 'your/path/to/scannet/scannet_2cm_sdf' which used in 2.Extract SDF inputs from ScanNet scenes
> > > ''' python data_processing/generate_sdfs_from_scannet_scenes.py --sdf_path your/path/to/scannet/scannet_2cm_sdf --scan_path your/path/to/ScanNet/public/v2/scans --mask_path dataset_samples/scannet '''
> > 
> > 
> > Hi,
> > Thanks a lot for your interest. You need to sign the agreements for ScanNet and ShapeNet to get the dataset from their original website first, and then use these datasets as the original. We'll try to release our own dataset as well (try to figure out how now).
> > ShapeNet: https://shapenet.org/ ; ScanNet: https://github.com/ScanNet/ScanNet
> > Best, Yuchen
> 
> Thanks for you quickly reply. I have downloaded the scannet datasets, but there is no sdf data here. I am not sure how you generate sdf files. Is ok to use this repo https://github.com/andyzeng/tsdf-fusion-python? And there are some params that didn't be figure out in origin paper. Can you help to figure it out? Thanks!!
> 
> Shiyang

Hi Shiyang,

I have released the dataset. Feel free to check the new README file, and please let me know if it doesn't work. Thanks~

Best,
Yuchen

**Comment by saladcat** [comment]
> > > > Thanks for your great works, I find there are some data missing here. How can I generate 'your/path/to/scannet/scannet_2cm_sdf' which used in 2.Extract SDF inputs from ScanNet scenes
> > > > ''' python data_processing/generate_sdfs_from_scannet_scenes.py --sdf_path your/path/to/scannet/scannet_2cm_sdf --scan_path your/path/to/ScanNet/public/v2/scans --mask_path dataset_samples/scannet '''
> > > 
> > > 
> > > Hi,
> > > Thanks a lot for your interest. You need to sign the agreements for ScanNet and ShapeNet to get the dataset from their original website first, and then use these datasets as the original. We'll try to release our own dataset as well (try to figure out how now).
> > > ShapeNet: https://shapenet.org/ ; ScanNet: https://github.com/ScanNet/ScanNet
> > > Best, Yuchen
> > 
> > 
> > Thanks for you quickly reply. I have downloaded the scannet datasets, but there is no sdf data here. I am not sure how you generate sdf files. Is ok to use this repo https://github.com/andyzeng/tsdf-fusion-python? And there are some params that didn't be figure out in origin paper. Can you help to figure it out? Thanks!!
> > Shiyang
> 
> Hi Shiyang,
> 
> I have released the dataset. Feel free to check the new README file, and please let me know if it doesn't work. Thanks~
> 
> Best, Yuchen

I run cmd
'''
python training.py --data_path data/shapenet --train_file shapenet.txt --val_trained_file shapenet.txt --val_novel_file shapenet.txt --truncation 2.5 --patch_res 32 --dataset shapenet --model_stage patch_learning
'''
error as following:
```
Traceback (most recent call last):
  File "training.py", line 430, in <module>
    main()
  File "training.py", line 425, in main
    train(device, model_refine, dataloaders, args.save_epoch, args.step, args.num_epochs, args.model_stage, args.output_path, args.truncation, args.lr, args.no_wall_aug, args.patch_res)
  File "training.py", line 206, in train
    shape_priors_generated, _, _, _ = model(inputs)
  File "/home/zsy/anaconda3/envs/patch_comp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zsy/vsc-code/PatchComplete/model/patch_learning_models.py", line 182, in forward
    learned_weights = torch.matmul(patch_features, prior_features.transpose(1, 0))
RuntimeError: mat1 dim 1 must match mat2 dim 0
```

it seems the preprocess shapennet is wrong.

**Comment by yuchenrao** [comment]
> 

Hi Shiyang,

I have uploaded the related files (train / test / val) and could you double check the updated readme?

Thanks a lot!

Best,
Yuchen

**Comment by yuchenrao** [comment]
> > > > > Thanks for your great works, I find there are some data missing here. How can I generate 'your/path/to/scannet/scannet_2cm_sdf' which used in 2.Extract SDF inputs from ScanNet scenes
> > > > > ''' python data_processing/generate_sdfs_from_scannet_scenes.py --sdf_path your/path/to/scannet/scannet_2cm_sdf --scan_path your/path/to/ScanNet/public/v2/scans --mask_path dataset_samples/scannet '''
> > > > 
> > > > 
> > > > Hi,
> > > > Thanks a lot for your interest. You need to sign the agreements for ScanNet and ShapeNet to get the dataset from their original website first, and then use these datasets as the original. We'll try to release our own dataset as well (try to figure out how now).
> > > > ShapeNet: https://shapenet.org/ ; ScanNet: https://github.com/ScanNet/ScanNet
> > > > Best, Yuchen
> > > 
> > > 
> > > Thanks for you quickly reply. I have downloaded the scannet datasets, but there is no sdf data here. I am not sure how you generate sdf files. Is ok to use this repo https://github.com/andyzeng/tsdf-fusion-python? And there are some params that didn't be figure out in origin paper. Can you help to figure it out? Thanks!!
> > > Shiyang
> > 
> > 
> > Hi Shiyang,
> > I have released the dataset. Feel free to check the new README file, and please let me know if it doesn't work. Thanks~
> > Best, Yuchen
> 
> I run cmd ''' python training.py --data_path data/shapenet --train_file shapenet.txt --val_trained_file shapenet.txt --val_novel_file shapenet.txt --truncation 2.5 --patch_res 32 --dataset shapenet --model_stage patch_learning ''' error as following:
> 
> ```
> Traceback (most recent call last):
>   File "training.py", line 430, in <module>
>     main()
>   File "training.py", line 425, in main
>     train(device, model_refine, dataloaders, args.save_epoch, args.step, args.num_epochs, args.model_stage, args.output_path, args.truncation, args.lr, args.no_wall_aug, args.patch_res)
>   File "training.py", line 206, in train
>     shape_priors_generated, _, _, _ = model(inputs)
>   File "/home/zsy/anaconda3/envs/patch_comp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/zsy/vsc-code/PatchComplete/model/patch_learning_models.py", line 182, in forward
>     learned_weights = torch.matmul(patch_features, prior_features.transpose(1, 0))
> RuntimeError: mat1 dim 1 must match mat2 dim 0
> ```
> 
> it seems the preprocess shapennet is wrong.

Hi Shiyang,

I have uploaded the related files (train / test / val) and could you double check the updated readme?

Thanks a lot!

Best,
Yuchen
