### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by list17** [yuchenrao/PatchComplete#2]
1. when running 

> python training.py --data_path data/shapenet --train_file txt_files/shapenet_train.txt --val_trained_file txt_files/shapenet_val.txt --val_novel_file txt_files/shapenet_val_novel.txt --truncation 2.5 --patch_res 32 --dataset shapenet --model_stage 

/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/loss.py:921: UserWarning: Using a target size (torch.Size([32, 1, 128, 128, 128])) that is different to the input size (torch.Size([32, 1, 32, 32, 32])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta)
Traceback (most recent call last):
  File "training.py", line 430, in <module>
    main()
  File "training.py", line 425, in main
    train(device, model_refine, dataloaders, args.save_epoch, args.step, args.num_epochs, args.model_stage, args.output_path, args.truncation, args.lr, args.no_wall_aug, args.patch_res)
  File "training.py", line 207, in train
    loss = calc_loss_l1_weighted(shape_priors_generated, labels, metrics, '')
  File "training.py", line 23, in calc_loss_l1_weighted
    loss_l1_ori = criterion_l1(shape_priors, target_sdf)
  File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 921, in forward
    return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta)
  File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/functional.py", line 2997, in smooth_l1_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/functional.py", line 73, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (32) must match the size of tensor b (128) at non-singleton dimension 4

2. And I want to know whether the pretrained model will be released?

**Comment by yuchenrao** [comment]
> 1. when running
> 
> > python training.py --data_path data/shapenet --train_file txt_files/shapenet_train.txt --val_trained_file txt_files/shapenet_val.txt --val_novel_file txt_files/shapenet_val_novel.txt --truncation 2.5 --patch_res 32 --dataset shapenet --model_stage
> 
> /home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/loss.py:921: UserWarning: Using a target size (torch.Size([32, 1, 128, 128, 128])) that is different to the input size (torch.Size([32, 1, 32, 32, 32])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size. return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta) Traceback (most recent call last): File "training.py", line 430, in main() File "training.py", line 425, in main train(device, model_refine, dataloaders, args.save_epoch, args.step, args.num_epochs, args.model_stage, args.output_path, args.truncation, args.lr, args.no_wall_aug, args.patch_res) File "training.py", line 207, in train loss = calc_loss_l1_weighted(shape_priors_generated, labels, metrics, '') File "training.py", line 23, in calc_loss_l1_weighted loss_l1_ori = criterion_l1(shape_priors, target_sdf) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl return forward_call(*input, **kwargs) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 921, in forward return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/functional.py", line 2997, in smooth_l1_loss expanded_input, expanded_target = torch.broadcast_tensors(input, target) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/functional.py", line 73, in broadcast_tensors return _VF.broadcast_tensors(tensors) # type: ignore[attr-defined] RuntimeError: The size of tensor a (32) must match the size of tensor b (128) at non-singleton dimension 4
> 
> 2. And I want to know whether the pretrained model will be released?

1. Could you re-download the shapenet dataset? I fix it and it should work now. Sorry about the inconvenience.
2. I'll release the pretrain model hopefully this week. 

Best,
Yuchen

**Comment by list17** [comment]
> > 1. when running
> > 
> > > python training.py --data_path data/shapenet --train_file txt_files/shapenet_train.txt --val_trained_file txt_files/shapenet_val.txt --val_novel_file txt_files/shapenet_val_novel.txt --truncation 2.5 --patch_res 32 --dataset shapenet --model_stage
> > 
> > 
> > /home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/loss.py:921: UserWarning: Using a target size (torch.Size([32, 1, 128, 128, 128])) that is different to the input size (torch.Size([32, 1, 32, 32, 32])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size. return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta) Traceback (most recent call last): File "training.py", line 430, in main() File "training.py", line 425, in main train(device, model_refine, dataloaders, args.save_epoch, args.step, args.num_epochs, args.model_stage, args.output_path, args.truncation, args.lr, args.no_wall_aug, args.patch_res) File "training.py", line 207, in train loss = calc_loss_l1_weighted(shape_priors_generated, labels, metrics, '') File "training.py", line 23, in calc_loss_l1_weighted loss_l1_ori = criterion_l1(shape_priors, target_sdf) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl return forward_call(*input, **kwargs) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 921, in forward return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/functional.py", line 2997, in smooth_l1_loss expanded_input, expanded_target = torch.broadcast_tensors(input, target) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/functional.py", line 73, in broadcast_tensors return _VF.broadcast_tensors(tensors) # type: ignore[attr-defined] RuntimeError: The size of tensor a (32) must match the size of tensor b (128) at non-singleton dimension 4
> > 
> > 2. And I want to know whether the pretrained model will be released?
> 
> 1. Could you re-download the shapenet dataset? I fix it and it should work now. Sorry about the inconvenience.
> 2. I'll release the pretrain model hopefully this week.
> 
> Best, Yuchen

1. Thanks for your reply! I tried the new dataset and there is no error. However, the iou becomes nan when running the same command. Is this normal?
![image](https://user-images.githubusercontent.com/37865076/201134837-c718551e-b0da-452a-8474-fb10138fcf56.png)

2. https://github.com/yuchenrao/PatchComplete/blob/03cfd77221a79d5eb2e64cfa32ceb9f6899b4bd3/training.py#L361
Do we need to pass the arg.patch_res to create the dataset when training on different resolution data?

**Comment by yuchenrao** [comment]
> > > 1. when running
> > > 
> > > > python training.py --data_path data/shapenet --train_file txt_files/shapenet_train.txt --val_trained_file txt_files/shapenet_val.txt --val_novel_file txt_files/shapenet_val_novel.txt --truncation 2.5 --patch_res 32 --dataset shapenet --model_stage
> > > 
> > > 
> > > /home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/loss.py:921: UserWarning: Using a target size (torch.Size([32, 1, 128, 128, 128])) that is different to the input size (torch.Size([32, 1, 32, 32, 32])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size. return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta) Traceback (most recent call last): File "training.py", line 430, in main() File "training.py", line 425, in main train(device, model_refine, dataloaders, args.save_epoch, args.step, args.num_epochs, args.model_stage, args.output_path, args.truncation, args.lr, args.no_wall_aug, args.patch_res) File "training.py", line 207, in train loss = calc_loss_l1_weighted(shape_priors_generated, labels, metrics, '') File "training.py", line 23, in calc_loss_l1_weighted loss_l1_ori = criterion_l1(shape_priors, target_sdf) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl return forward_call(*input, **kwargs) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 921, in forward return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/nn/functional.py", line 2997, in smooth_l1_loss expanded_input, expanded_target = torch.broadcast_tensors(input, target) File "/home/lst/anaconda3/envs/npull/lib/python3.8/site-packages/torch/functional.py", line 73, in broadcast_tensors return _VF.broadcast_tensors(tensors) # type: ignore[attr-defined] RuntimeError: The size of tensor a (32) must match the size of tensor b (128) at non-singleton dimension 4
> > > 
> > > 2. And I want to know whether the pretrained model will be released?
> > 
> > 
> > 
> > 1. Could you re-download the shapenet dataset? I fix it and it should work now. Sorry about the inconvenience.
> > 2. I'll release the pretrain model hopefully this week.
> > 
> > Best, Yuchen
> 
> 1. Thanks for your reply! I tried the new dataset and there is no error. However, the iou becomes nan when running the same command. Is this normal?
>    ![image](https://user-images.githubusercontent.com/37865076/201134837-c718551e-b0da-452a-8474-fb10138fcf56.png)
> 2. https://github.com/yuchenrao/PatchComplete/blob/03cfd77221a79d5eb2e64cfa32ceb9f6899b4bd3/training.py#L361
>    
>    Do we need to pass the arg.patch_res to create the dataset when training on different resolution data?

Hi,

1. It happened before, but I thought I fixed this problem... The reason is that I do data augmentation on the fly, and during training, it may have empty GTs in some cases. You can ignore these samples if sum(gt)==0, I can fix it later as well. But overall it shouldn't affect the results too much. Please let me know if there are something wrong in the end. Thx!

2.  patch_resolution represents the resolution for patch learning, in our case: 4, 8, 32, which should affect the model rather than the input data; For input data, we only support 32 cube. Our method should be easy to fit higher resolution dataset, e.g. 64 and 128, but you may need to generate datasets on your own.

Best,
Yuchen
