### ISSUE TITLE
Will you release the pre-trained model?

### ISSUE THREAD

**Issue by astaka-pe** [yuchenrao/PatchComplete#4]
Hi, thanks for the great work!

I'm interested in shape restoration (especially mesh). 
Will you release the pre-trained model for ShapeNet and ScanNet?

Thanks in advance.

**Comment by yuchenrao** [comment]
> Hi, thanks for the great work!
> 
> I'm interested in shape restoration (especially mesh). Will you release the pre-trained model for ShapeNet and ScanNet?
> 
> Thanks in advance.

Sorry for the late replay, just delivered the pre-trained models. Please let me know it you meet any problems.
