### ISSUE TITLE
preprocess data and visualize output question. 

### ISSUE THREAD

**Issue by saladcat** [yuchenrao/PatchComplete#5]
thanks for your great works, and share it with us. I have two question about this repo.
1. processed data in shapenet. there are some input_*.npz files, is that random incomplete SDF for CAD? why you name 4~7? I didn't find the cospending code in [depth_renderer](https://github.com/yinyunie/depth_renderer/) which you mentioned in README.md. 
'''
├── gt.npz
├── gt.off
├── input_4.npz
├── input_5.npz
├── input_6.npz
└── input_7.npz
'''
2. How can we visual the output file(*.npz). Could you provide a visual script. it's really helpful.

**Comment by saladcat** [comment]
I visual sdf use marching cubes in evaluation. but the result is far away from paper reported. did i do something wrong?
<img width="804" alt="image" src="https://user-images.githubusercontent.com/22851795/216273275-90ff76f4-63bb-4df6-ae63-7e64a1f5867b.png">

papers reported as following.
<img width="923" alt="image" src="https://user-images.githubusercontent.com/22851795/216273400-337952d8-7a91-413a-b134-1ed17bc344df.png">

**Comment by yuchenrao** [comment]
Hi,

Thanks a lot for reaching out. Here are the answers:
1. 4-7 are the index for the views among 20 views, which mimic the view direction of the scannet, which is not that important.
2. You can directly meshlab or other 3D visualization libs e.g. open3d, which should be the same as what you did for the third questions
3. It seems reasonable on my side, since I am using smooth for paper visualization. Without that, the visualization actually seems reasonable. If you want to get much smoother results, you need to increase the rendering/fusion resolution, e.g. 128.

Best,
Yuchen

**Comment by KatherineLiu-TRI** [comment]
Hi @yuchenrao, not the OP but these answers are helpful, thank you!

Could you elaborate on how you generated the visualizations in Figure 6 above? Specifically,

- What do you mean by "smooth" and increasing the rendering/fusion resolution? Are you using a specific third party library for rendering and if so, what library?
- How are you extracting the partial surface from the partial SDF?

I appreciate any pointers!

**Comment by yuchenrao** [comment]
> Hi @yuchenrao, not the OP but these answers are helpful, thank you!
> 
> Could you elaborate on how you generated the visualizations in Figure 6 above? Specifically,
> 
> * What do you mean by "smooth" and increasing the rendering/fusion resolution? Are you using a specific third party library for rendering and if so, what library?
> * How are you extracting the partial surface from the partial SDF?
> 
> I appreciate any pointers!

Hi, 

1. The visualization is smoothed by blander, which you can find a smooth option for it.
2. The partial SDF is extracted based on the distance value, you can extract it if the abs(distance) is smaller than a voxel_grid, or voxel_grid  > distance > 0.

Best,
Yuchen

**Comment by KatherineLiu-TRI** [comment]
Thank you! Another clarifying question re: the partial SDF. Are you saying that you alter the SDF grid values so that if abs(distance) < voxel_grid you set the distance to be > voxel_grid and then run marching cubes again?

**Comment by yuchenrao** [comment]
> Thank you! Another clarifying question re: the partial SDF. Are you saying that you alter the SDF grid values so that if abs(distance) < voxel_grid you set the distance to be > voxel_grid and then run marching cubes again?

No, I mean you can only show the grid with the value that: 1. abs(value) < voxel_grid; 2. the value is in the range of [0, voxel_grid]. I don't remember which way I was using, but I think either of them should be fine.

**Comment by KatherineLiu-TRI** [comment]
Thank you for the response!

**Comment by theycallmefm** [comment]
@yuchenrao Hi, I also want a clarification on input data if it is possible.  Are you using same view points stated in here? 
https://github.com/yinyunie/depth_renderer/blob/main/create_viewpoints.py

That means input_4, input_5... corresponds to 4th, 5th, 6th and 7th index in the loop? If not can you give your view parameters?

**Comment by yuchenrao** [comment]
> [@yuchenrao](https://github.com/yuchenrao) Hi, I also want a clarification on input data if it is possible. Are you using same view points stated in here? https://github.com/yinyunie/depth_renderer/blob/main/create_viewpoints.py
> 
> That means input_4, input_5... corresponds to 4th, 5th, 6th and 7th index in the loop? If not can you give your view parameters?

Yes, you are right.

**Comment by theycallmefm** [comment]
For those who working on depth renderer know that camera parameter outputs in depth renderer start at indice 1, so cam_RT_005, cam_RT_006, cam_RT_007, cam_RT_008 corresponds to  input_4, input_5, input_6, input_7 respectively

@yuchenrao  I have another followup question regarding your data.  I am using this for creating .off files 
https://github.com/yinyunie/depth_renderer/blob/main/depth_fusion.py

for generating data I set 
```
voxel_res = 32
truncation_factor = 3
```
If I want incomplete shape, for example in this case `input_4.npz` I set this under view_ids
```
total_view_nums = 1
view_ids = [5]
```

is this correct? I compared my generated model from whole views and `gt.off` from your data_samples and it seems equivalent. But when I extract mesh from input npz files size it seems off. How do you generate your npz files after creating your off files?
