### ISSUE TITLE
how to get the partial data?

### ISSUE THREAD

**Issue by CRISZJ** [yuchenrao/PatchComplete#8]
Hello, how can I get the incomplete shape? I found that depth_renderer does not have relevant code.

**Comment by yuchenrao** [comment]
Hi, depth render can provide sdf for each view, you can use that as the incomplete shape.

**Comment by CRISZJ** [comment]
> Hi, depth render can provide sdf for each view, you can use that as the incomplete shape.

I'll try it, thanks for your kindly reply!!!

**Comment by CRISZJ** [comment]
> Hi, depth render can provide sdf for each view, you can use that as the incomplete shape.

I've try, but I met some problems. I generate the partial shape based on the perspective. Sometimes it succeeds, but sometimes it fails, like the following：
success:
![image](https://github.com/yuchenrao/PatchComplete/assets/38414011/d13fa3dc-f8ad-4916-bb7b-c58641a3f6b1)
failure:
![image](https://github.com/yuchenrao/PatchComplete/assets/38414011/08a980ce-8212-4670-a7d0-6adc5191abf3)

In terms of method, we ran normalize_shape.py, create_viewpoints.py, run_render.py and then used the depth map to run depth_fusion.py to directly generate the results. Are there any errors in our execution?
Looking forward to your reply!

**Comment by yuchenrao** [comment]
> > Hi, depth render can provide sdf for each view, you can use that as the incomplete shape.
> 
> I've try, but I met some problems. I generate the partial shape based on the perspective. Sometimes it succeeds, but sometimes it fails, like the following： success: ![image](https://private-user-images.githubusercontent.com/38414011/293169936-d13fa3dc-f8ad-4916-bb7b-c58641a3f6b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDEyNzIsIm5iZiI6MTcwNTkwMDk3MiwicGF0aCI6Ii8zODQxNDAxMS8yOTMxNjk5MzYtZDEzZmEzZGMtZjhhZC00OTE2LWJiN2ItYzU4NjQxYTNmNmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA1MjI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NDBkZGRmMzAzNjJlODU3ZWRjNTI4Y2QxODE4YzA5MzUyOWRmZTIyYTJiZDQyNDYxNjg1YWYzNWJiYTQ0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RTuLgCHD0EaEobZttjjJmzFn91aCJ5G8eU9ArXwGlng) failure: ![image](https://private-user-images.githubusercontent.com/38414011/293170346-08a980ce-8212-4670-a7d0-6adc5191abf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDEyNzIsIm5iZiI6MTcwNTkwMDk3MiwicGF0aCI6Ii8zODQxNDAxMS8yOTMxNzAzNDYtMDhhOTgwY2UtODIxMi00NjcwLWE3ZDAtNmFkYzUxOTFhYmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA1MjI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOGY3MDVhMTg4ZGVkYjk3YzM2ZGJjNGFhM2U2MDM2ZmMxMzgxYmQwYWZiYWEzMTdhYjEwM2RlMGE0NDFkYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DpG6MD7YE3_SR9BXcEAXA_7wLBH2aB3dovAIe2VQyy4)
> 
> In terms of method, we ran normalize_shape.py, create_viewpoints.py, run_render.py and then used the depth map to run depth_fusion.py to directly generate the results. Are there any errors in our execution? Looking forward to your reply!


Hi,

I am not sure what happened here, maybe check the camera view for the failure cases to see whether there are something wrong of the camera view. Also this seems a problem for depth render, maybe you could also leave a question on that repo.

Best,
Yuchen

**Comment by CRISZJ** [comment]
ok, thanks
